[package]
name = "day-7"
version = "0.1.0"
authors = ["Duncan Dean <duncangleeddean@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
petgraph = "0.5.1"
